### PR TITLE
🐛 Fix penalty shootouts angle

### LINKED ISSUE #22: Wrong repositioning in penalty shootout condition
**Describe the bug**
The angle of each robot is wrong in the repositioning. 

**To Reproduce**
1. Sending information of each robots position
2. Referee receives the right position(x,y).
3. The angle is the only thing wrong in this condition.

**Expected behavior**
Repositioning with right angle.

**Screenshots**
Wrong repositioning:
image
Right repositioning:
image

**Desktop (please complete the following information):**
 - OS: [e.g. Ubuntu 18.04]

### PR DESCRIPTION
**Pull request by LucasHaug**
Hello, as described in the issue #22, there is a problem with the penalty angle when the game state is "Penalty Shootouts", because the angle stored in the `Angle` class is in radians, but I think that in the lines in which I made the changes, degrees were used, so that calling the `setValue` method would cause a value in degrees to be in the range 0 to 2π, without first converting it to radians. I'm not very familiar with the VSSReferee code, but from what I've tested, it seems to be working.

### CODE REVIEW

File: src/world/entities/replacer/replacer.cpp [hunk 1]
```diff
@@ -538,7 +538,7 @@ VSSRef::Frame Replacer::getOutsideFieldPlacement(VSSRef::Color teamColor){
 
     // Place each robot outside field
     for(int i = 0; i < players.size(); i++) {
-        PlaceData toPlace(Position(true, ((i+1) * 2*getConstants()->robotLength()) + (i * sideLength/players.size()), 1.1*fieldWidth), Angle(true, 90.0f));
+        PlaceData toPlace(Position(true, ((i+1) * 2*getConstants()->robotLength()) + (i * sideLength/players.size()), 1.1*fieldWidth), Angle(true, Angle::pi / 2.0);
```
Comment (LucasHaug) [inline src/world/entities/replacer/replacer.cpp]:
```suggestion
        PlaceData toPlace(Position(true, ((i+1) * 2*getConstants()->robotLength()) + (i * sideLength/players.size()), 1.1*fieldWidth), Angle(true, Angle::pi / 2.0));
```

**Review by zsmn — APPROVED** [review]
