### PR TITLE
Inserted world class, vision basic structure and RefereeCore class

### LINKED ISSUE #3: World class
The world class will be primarily responsible for the maintenance of all other entities in the system.
It must maintain a Hash Table whose key will be the priority of the entities, so that we can initialize and finish them in an defined sequence (avoiding crashes or bugs by dependencies and null pointers).

### PR DESCRIPTION
**Pull request by zsmn**

### CODE REVIEW

File: main.cpp [hunk 1]
```diff
@@ -18,7 +19,15 @@ int main(int argc, char *argv[])
     ExitHandler::setApplication(&app);
     ExitHandler::setup();
 
+    // Initializating referee core
+    RefereeCore *refereeCore = new RefereeCore();
```
Comment (zsmn) [inline main.cpp:23]: The **RefereeCore** class will be responsible for creating all pointers to the program modules and their instantiation in the World class, which will subsequently maintain these modules.

File: src/refereecore.cpp [hunk 2]
```diff
@@ -0,0 +1,25 @@
...
+    _world = new World();
+}
+
+RefereeCore::~RefereeCore() {
+    // Deleting world module
+    delete _world;
+}
+
+void RefereeCore::start() {
+    // Creating vision pointer and adding it to world with priority 0
```
Comment (zsmn) [inline src/refereecore.cpp:14]: The **start()** method in **RefereeCore** class will create the module pointers and insert them into World module

File: src/refereecore.cpp [hunk 3]
```diff
@@ -0,0 +1,25 @@
...
+    _vision = new Vision();
+    _world->addEntity(_vision, 0);
+
+    // Starting entities
+    _world->startEntities();
+}
+
+void RefereeCore::stop() {
```
Comment (zsmn) [inline src/refereecore.cpp:22]: The **stop()** method in **RefereeCore** class will make **World** class stop and delete all modules.

File: src/world/world.cpp [hunk 4]
```diff
@@ -0,0 +1,89 @@
...
+
+void World::addEntity(Entity *entity, int entityPriotity) {
+    // Check if priority is already created
+    if(!_worldEntities.keys().contains(entityPriotity)) {
+        // Create it
+        _worldEntities.insert(entityPriotity, new QHash<int, Entity*>());
+    }
+
+    // Take entities registered with 'entityPriority' priority
+    QHash<int, Entity*> *prioEntities = _worldEntities.value(entityPriotity);
```
Comment (zsmn) [inline src/world/world.cpp:15]: An pointer to hash has used to avoid catching only an copy from **QMap** class

File: src/world/world.cpp [hunk 5]
```diff
@@ -0,0 +1,89 @@
...
+    entity->setPriority(entityPriotity);
+}
+
+void World::startEntities() {
+    // Get priorities in hash
+    QList<int> priorities = _worldEntities.keys();
+
+    // In each priority (decreasing, most priority first)
+    const int prioritiesSize = priorities.size();
+    for(int i = prioritiesSize - 1; i >= 0; i--) {
```
Comment (zsmn) [inline src/world/world.cpp:30]: This will take priorities sorted by the higher to lower, **so the entity with the most higher priority will be started first!**

File: src/world/world.cpp [hunk 6]
```diff
@@ -0,0 +1,89 @@
...
+    }
+}
+
+void World::stopAndDeleteEntities() {
+    // Get priorities in hash
+    QList<int> priorities = _worldEntities.keys();
+
+    // In each priority (increasing)
+    const int prioritiesSize = priorities.size();
+    for(int i = 0; i < prioritiesSize; i++) {
```
Comment (zsmn) [inline src/world/world.cpp:58]: This will take priorities sorted by the lower to higher, **so the entity with the less priority will be stopped first!**
